In [169]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from numpy import isclose

import matplotlib.pyplot as plt

In [170]:
data = datasets.load_iris()

print(type(data))
# print(data)

# plt.scatter(data.data, data.target)

<class 'sklearn.utils._bunch.Bunch'>


In [171]:
data = datasets.load_iris()

X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=123
)

In [172]:
# This is a 2d array of the features of our dataset
X_train[:5]

array([[6.5, 3.2, 5.1, 2. ],
       [5.1, 3.3, 1.7, 0.5],
       [4.9, 3.1, 1.5, 0.1],
       [6.7, 3.1, 4.7, 1.5],
       [6.1, 3. , 4.6, 1.4]])

In [173]:
y_train[:5]

array([2, 0, 0, 1, 1])

In [174]:
# sample_x_train = data[:10].to_numpy()

In [175]:
# Eucledian Distance
def euclidean_distance(q, p):
    distance = 0
    for i in range(len(q)):
        distance += (q[i] - p[i])**2

    return distance**0.5

In [176]:
# Primitive
def my_euclidean_distance(q, p) -> float:
    assert len(q) == len(p), (
        "Vectors must be of the same length"
    )
    distance = 0
    for i in range(len(q)):
        distance += (q[i] - p[i])**2
    return distance**0.5

In [177]:
# Switch to np methods
def my_euclidean_distance(q, p) -> float:
    assert len(q) == len(p), (
        "Vectors must be of the same length"
    )
    distance = 0
    for i in range(len(q)):
        distance += np.square(q[i] - p[i])
    return np.sqrt(distance)

In [178]:
# Replace for loop with np.sum
def my_euclidean_distance(q, p) -> float:
    assert len(q) == len(p), (
        "Vectors must be of the same length"
    )
    distance = np.sqrt(np.sum(np.square(q - p)))
    return distance

In [179]:
# Just use np.linalg.norm
# np.linalg.norm(p - q)

In [180]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.linalg.norm(arr1 - arr2))
print(my_euclidean_distance(arr1, arr2))
assert isclose(np.linalg.norm(arr1 - arr2), my_euclidean_distance(arr1, arr2)), (
    "They are not equal!"
)
print("Yes, they are equal!")

5.196152422706632
5.196152422706632
Yes, they are equal!


In [181]:
data = datasets.load_iris()

X = data.data[:10]
y = data.target[:10]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=123
)

In [182]:
X_train

array([[4.4, 2.9, 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.9, 3.1, 1.5, 0.1],
       [4.7, 3.2, 1.3, 0.2]])

In [183]:
X_test

array([[5. , 3.6, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5. , 3.4, 1.5, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

In [184]:
y_train

array([0, 0, 0, 0, 0, 0])

In [185]:
y_test

array([0, 0, 0, 0])

In [186]:
distance = np.zeros((len(X_test), len(X_train)))

for i_test, X_test_vector in enumerate(X_test):
    for i_train, X_train_vector in enumerate(X_train):
        distance[i_test][i_train] = my_euclidean_distance(
            X_test_vector, X_train_vector
        )
    print(f"Test vector {i_test}: {np.round(distance[i_test], 2)}")

# print(np.round(distance, 2))

Test vector 0: [0.92 0.65 0.61 0.46 0.53 0.51]
Test vector 1: [0.92 0.65 0.54 0.52 0.47 0.51]
Test vector 2: [0.79 0.5  0.42 0.42 0.33 0.41]
Test vector 3: [1.46 1.17 1.09 0.99 1.01 1.09]


In [187]:
# for every vector in X_test:
#     calculate the distance between that vector and all known data points in X_train

distance = np.zeros((len(X_test), len(X_train)))

for i_test, X_test_vector in enumerate(X_test):
    for i_train, X_train_vector in enumerate(X_train):
        distance[i_test][i_train] = my_euclidean_distance(
            X_test_vector, X_train_vector
        )

print(np.round(distance, 2))

[[0.92 0.65 0.61 0.46 0.53 0.51]
 [0.92 0.65 0.54 0.52 0.47 0.51]
 [0.79 0.5  0.42 0.42 0.33 0.41]
 [1.46 1.17 1.09 0.99 1.01 1.09]]


In [188]:
# for every vector in X_test:
#     calculate the distance between that vector and all known data points in X_train

distance = np.zeros((len(X_test), len(X_train)))

for i_test, X_test_vector in enumerate(X_test):
    for i_train, X_train_vector in enumerate(X_train):
        distance[i_test][i_train] = np.linalg.norm(
            X_test_vector - X_train_vector
        )

print(np.round(distance, 2))

[[0.92 0.65 0.61 0.46 0.53 0.51]
 [0.92 0.65 0.54 0.52 0.47 0.51]
 [0.79 0.5  0.42 0.42 0.33 0.41]
 [1.46 1.17 1.09 0.99 1.01 1.09]]


In [189]:
X_test

array([[5. , 3.6, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5. , 3.4, 1.5, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

In [190]:
X_test**2

array([[25.  , 12.96,  1.96,  0.04],
       [26.01, 12.25,  1.96,  0.04],
       [25.  , 11.56,  2.25,  0.04],
       [29.16, 15.21,  2.89,  0.16]])

In [191]:
np.dot(X_test**2, X_train.T**2)

array([[596.8368, 657.9572, 720.7332, 682.6628, 729.206 , 688.2744],
       [610.4193, 672.5057, 738.5933, 695.8268, 746.633 , 703.3149],
       [585.6312, 645.1557, 708.7016, 667.0472, 716.4045, 674.4285],
       [698.1245, 769.7026, 842.6924, 798.532 , 852.8038, 804.7853]])

In [192]:
from scipy.ndimage import convolve
convolve(X_test**2, X_train.T**2)


array([[2676.7033, 2259.4318, 1427.3821,  906.9782],
       [3018.5313, 2525.8435, 1627.1936, 1082.7137],
       [3177.9102, 2653.7591, 1717.7932, 1164.2839],
       [2838.2391, 2389.7233, 1525.1564,  995.2944]])